# Generated by Django 5.2.8 on 2026-03-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_trailerrecommendation"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market", models.CharField(blank=True, max_length=24)),
                ("symbol", models.CharField(max_length=32)),
                ("interval", models.CharField(max_length=12)),
                ("provider", models.CharField(blank=True, max_length=40)),
                ("provider_label", models.CharField(blank=True, max_length=80)),
                ("symbol_resolved", models.CharField(blank=True, max_length=32)),
                ("trend", models.CharField(blank=True, max_length=16)),
                ("entry", models.FloatField(blank=True, null=True)),
                ("stop_loss", models.FloatField(blank=True, null=True)),
                ("t1", models.FloatField(blank=True, null=True)),
                ("t2", models.FloatField(blank=True, null=True)),
                ("t3", models.FloatField(blank=True, null=True)),
                ("t4", models.FloatField(blank=True, null=True)),
                ("price_at_call", models.FloatField(blank=True, null=True)),
                ("latest_price", models.FloatField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sl", "Stop Loss"),
                            ("tp1", "TP1"),
                            ("tp2", "TP2"),
                            ("tp3", "TP3"),
                            ("tp4", "TP4"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_price", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "interval", "outcome"],
                        name="core_market_symbol_456dda_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="core_market_created_5ab44f_idx"
                    ),
                ],
            },
        ),
    ]
