# Generated by Django 5.2.8 on 2026-03-25 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_marketprediction"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderHealthEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market", models.CharField(blank=True, max_length=24)),
                ("symbol", models.CharField(max_length=32)),
                ("interval", models.CharField(blank=True, max_length=12)),
                ("provider", models.CharField(max_length=40)),
                ("ok", models.BooleanField(default=False)),
                ("latency_ms", models.IntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "created_at"],
                        name="core_provid_provide_0e25bb_idx",
                    ),
                    models.Index(
                        fields=["symbol", "created_at"],
                        name="core_provid_symbol_621734_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AlertDeliveryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel", models.CharField(max_length=20)),
                ("status", models.CharField(default="sent", max_length=20)),
                ("message", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prediction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.marketprediction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["channel", "created_at"],
                        name="core_alertd_channel_a5bfc6_idx",
                    )
                ],
            },
        ),
    ]
