# Generated by Django 5.2.8 on 2026-03-25 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_providerhealthevent_alertdeliverylog"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdaptiveTradingPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=64, unique=True)),
                ("confidence_threshold", models.FloatField(default=58.0)),
                ("min_risk_reward", models.FloatField(default=1.25)),
                ("rollback_count", models.IntegerField(default=0)),
                ("preferred_sessions", models.JSONField(blank=True, default=list)),
                ("blocked_conditions", models.JSONField(blank=True, default=list)),
                ("preferred_conditions", models.JSONField(blank=True, default=list)),
                ("previous_state", models.JSONField(blank=True, default=dict)),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["scope"],
            },
        ),
        migrations.CreateModel(
            name="PaperTradingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("balance", models.FloatField(default=10000)),
                ("equity", models.FloatField(default=10000)),
                ("peak_equity", models.FloatField(default=10000)),
                ("max_drawdown_pct", models.FloatField(default=0)),
                ("max_risk_per_trade_pct", models.FloatField(default=1.0)),
                ("max_daily_drawdown_pct", models.FloatField(default=4.0)),
                ("max_session_drawdown_pct", models.FloatField(default=2.5)),
                ("daily_start_equity", models.FloatField(default=10000)),
                ("session_start_equity", models.FloatField(default=10000)),
                ("daily_drawdown_pct", models.FloatField(default=0)),
                ("session_drawdown_pct", models.FloatField(default=0)),
                ("last_risk_reset_at", models.DateTimeField(blank=True, null=True)),
                ("risk_state", models.CharField(default="normal", max_length=20)),
                ("win_count", models.IntegerField(default=0)),
                ("loss_count", models.IntegerField(default=0)),
                ("trade_count", models.IntegerField(default=0)),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="marketprediction",
            name="simulated_pnl",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="marketprediction",
            name="simulated_r_multiple",
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name="TradeLearningSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market", models.CharField(blank=True, max_length=24)),
                ("symbol", models.CharField(max_length=32)),
                ("interval", models.CharField(max_length=12)),
                ("trend", models.CharField(blank=True, max_length=16)),
                ("outcome", models.CharField(max_length=12)),
                ("confidence_score", models.FloatField(default=0)),
                ("risk_reward_ratio", models.FloatField(default=0)),
                ("stop_distance", models.FloatField(default=0)),
                ("stop_distance_pct", models.FloatField(default=0)),
                ("mae", models.FloatField(default=0)),
                ("mfe", models.FloatField(default=0)),
                ("trailing_stop_improvement", models.FloatField(default=0)),
                ("atr14", models.FloatField(blank=True, null=True)),
                ("close_slope_30", models.FloatField(blank=True, null=True)),
                ("learning_features", models.JSONField(blank=True, default=dict)),
                ("root_causes", models.JSONField(blank=True, default=list)),
                ("tp_drivers", models.JSONField(blank=True, default=list)),
                ("policy_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prediction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_snapshot",
                        to="core.marketprediction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "interval", "outcome"],
                        name="core_tradel_symbol_be99c5_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="core_tradel_created_c713dd_idx"
                    ),
                ],
            },
        ),
    ]
