# Generated by Django 5.2.8 on 2026-03-28 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_adaptivetradingpolicy_papertradingaccount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(max_length=40, unique=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("fixed", "Fixed amount"), ("percent", "Percentage")],
                        default="fixed",
                        max_length=12,
                    ),
                ),
                ("discount_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="ZAR", max_length=8)),
                ("is_global", models.BooleanField(default=True)),
                ("allowed_channels", models.JSONField(blank=True, default=list)),
                ("min_order_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("usage_limit", models.PositiveIntegerField(default=1)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("active_from", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["code"], name="core_vouche_code_2f8142_idx"),
                    models.Index(fields=["is_active", "expires_at"], name="core_vouche_is_acti_25e315_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VoucherRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=80)),
                ("customer_name", models.CharField(blank=True, max_length=120)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                ("channel", models.CharField(blank=True, max_length=40)),
                ("order_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("discount_applied", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("final_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="core.voucher",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["reference", "created_at"], name="core_vouche_referen_8d6337_idx"),
                    models.Index(fields=["channel", "created_at"], name="core_vouche_channel_8565b3_idx"),
                ],
            },
        ),
    ]