# Generated by Django 5.2.8 on 2026-03-28 00:30

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


def seed_catalog_items(apps, schema_editor):
    VoucherCatalogItem = apps.get_model("core", "VoucherCatalogItem")
    items = [
        {"provider": "MTN", "name": "MTN Airtime R29", "category": "airtime", "delivery_type": "topup", "face_value": Decimal("29.00"), "sale_price": Decimal("29.00"), "currency": "ZAR", "requires_recipient": True, "recipient_label": "Phone number"},
        {"provider": "Vodacom", "name": "Vodacom Airtime R55", "category": "airtime", "delivery_type": "topup", "face_value": Decimal("55.00"), "sale_price": Decimal("55.00"), "currency": "ZAR", "requires_recipient": True, "recipient_label": "Phone number"},
        {"provider": "Cell C", "name": "Cell C Data R99", "category": "data", "delivery_type": "topup", "face_value": Decimal("99.00"), "sale_price": Decimal("99.00"), "currency": "ZAR", "requires_recipient": True, "recipient_label": "Phone number"},
        {"provider": "Betway", "name": "Betway Voucher R100", "category": "betting", "delivery_type": "digital_voucher", "face_value": Decimal("100.00"), "sale_price": Decimal("100.00"), "currency": "ZAR", "requires_recipient": False, "recipient_label": ""},
        {"provider": "Hollywoodbets", "name": "Hollywoodbets Voucher R250", "category": "betting", "delivery_type": "digital_voucher", "face_value": Decimal("250.00"), "sale_price": Decimal("250.00"), "currency": "ZAR", "requires_recipient": False, "recipient_label": ""},
        {"provider": "Uber Eats", "name": "Uber Eats Food Voucher R150", "category": "food", "delivery_type": "digital_voucher", "face_value": Decimal("150.00"), "sale_price": Decimal("150.00"), "currency": "ZAR", "requires_recipient": False, "recipient_label": ""},
        {"provider": "Shoprite", "name": "Shoprite Food Voucher R200", "category": "food", "delivery_type": "digital_voucher", "face_value": Decimal("200.00"), "sale_price": Decimal("200.00"), "currency": "ZAR", "requires_recipient": False, "recipient_label": ""},
        {"provider": "Showmax", "name": "Showmax Entertainment Voucher R120", "category": "entertainment", "delivery_type": "digital_voucher", "face_value": Decimal("120.00"), "sale_price": Decimal("120.00"), "currency": "ZAR", "requires_recipient": False, "recipient_label": ""},
    ]
    for item in items:
        VoucherCatalogItem.objects.update_or_create(
            provider=item["provider"],
            name=item["name"],
            defaults=item,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_voucher_voucherredemption"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="initial_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="voucher",
            name="remaining_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="voucher",
            name="supported_categories",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="voucher",
            name="supported_providers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="voucher",
            name="voucher_kind",
            field=models.CharField(choices=[("discount", "Discount"), ("stored_value", "Stored value")], default="discount", max_length=20),
        ),
        migrations.AddIndex(
            model_name="voucher",
            index=models.Index(fields=["voucher_kind", "is_active"], name="core_vouche_voucher_4b7b52_idx"),
        ),
        migrations.CreateModel(
            name="VoucherCatalogItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=140)),
                ("provider", models.CharField(max_length=120)),
                ("category", models.CharField(choices=[("airtime", "Airtime"), ("betting", "Betting"), ("food", "Food"), ("data", "Data"), ("entertainment", "Entertainment"), ("electricity", "Electricity"), ("other", "Other")], default="other", max_length=24)),
                ("delivery_type", models.CharField(choices=[("digital_voucher", "Digital voucher"), ("topup", "Top up"), ("pin", "PIN")], default="digital_voucher", max_length=24)),
                ("face_value", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="ZAR", max_length=8)),
                ("requires_recipient", models.BooleanField(default=False)),
                ("recipient_label", models.CharField(blank=True, max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "provider", "name"],
                "indexes": [
                    models.Index(fields=["category", "provider"], name="core_vouche_categor_4b332a_idx"),
                    models.Index(fields=["is_active", "category"], name="core_vouche_is_acti_03b936_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VoucherPurchase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference", models.CharField(blank=True, max_length=80)),
                ("recipient_reference", models.CharField(blank=True, max_length=120)),
                ("customer_name", models.CharField(blank=True, max_length=120)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                ("channel", models.CharField(blank=True, max_length=40)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("total_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("fulfilled", "Fulfilled"), ("failed", "Failed")], default="pending", max_length=20)),
                ("fulfillment_code", models.CharField(blank=True, max_length=80)),
                ("fulfillment_details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchases", to="core.vouchercatalogitem")),
                ("voucher", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="purchases", to="core.voucher")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["reference", "created_at"], name="core_vouche_referen_b3bc83_idx"),
                    models.Index(fields=["status", "created_at"], name="core_vouche_status_7f8c40_idx"),
                ],
            },
        ),
        migrations.RunPython(seed_catalog_items, migrations.RunPython.noop),
    ]