from decimal import Decimal

from django.db import migrations, models


def seed_expanded_voucher_catalog(apps, schema_editor):
    VoucherCatalogItem = apps.get_model("core", "VoucherCatalogItem")
    items = [
        {
            "provider": "OTT Voucher",
            "name": "OTT Voucher R100",
            "category": "betting",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("100.00"),
            "sale_price": Decimal("100.00"),
            "currency": "ZAR",
            "requires_recipient": False,
            "recipient_label": "",
            "notes": "Accepted across Betway, Hollywoodbets, Interbet, Gbets, Playabets, Sunbet, and similar bookmakers.",
            "metadata": {"acceptedBy": ["betway", "hollywoodbets", "interbet", "gbets", "playabets", "sunbet"]},
        },
        {
            "provider": "1Voucher",
            "name": "1Voucher R100",
            "category": "betting",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("100.00"),
            "sale_price": Decimal("100.00"),
            "currency": "ZAR",
            "requires_recipient": False,
            "recipient_label": "",
            "notes": "Widely used across Betway, Hollywoodbets, Supabets, YesPlay, and more.",
            "metadata": {"acceptedBy": ["betway", "hollywoodbets", "supabets", "yesplay"]},
        },
        {
            "provider": "BluVoucher",
            "name": "BluVoucher R100",
            "category": "betting",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("100.00"),
            "sale_price": Decimal("100.00"),
            "currency": "ZAR",
            "requires_recipient": False,
            "recipient_label": "",
            "notes": "Supported by Betway, Supabets, Hollywoodbets, and related operators.",
            "metadata": {"acceptedBy": ["betway", "supabets", "hollywoodbets"]},
        },
        {
            "provider": "EasyPay Voucher",
            "name": "EasyPay Voucher R100",
            "category": "betting",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("100.00"),
            "sale_price": Decimal("100.00"),
            "currency": "ZAR",
            "requires_recipient": False,
            "recipient_label": "",
            "notes": "Used at Betway, Hollywoodbets, YesPlay, Gbets, and similar platforms.",
            "metadata": {"acceptedBy": ["betway", "hollywoodbets", "yesplay", "gbets"]},
        },
        {
            "provider": "EasyLoad Voucher",
            "name": "EasyLoad Voucher R100",
            "category": "betting",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("100.00"),
            "sale_price": Decimal("100.00"),
            "currency": "ZAR",
            "requires_recipient": False,
            "recipient_label": "",
            "notes": "Used by several South African bookmakers.",
            "metadata": {"acceptedBy": ["south-african-bookmakers"]},
        },
        {
            "provider": "Kazang Voucher",
            "name": "Kazang Voucher R100",
            "category": "betting",
            "delivery_type": "pin",
            "face_value": Decimal("100.00"),
            "sale_price": Decimal("100.00"),
            "currency": "ZAR",
            "requires_recipient": False,
            "recipient_label": "",
            "notes": "Can be used for betting, airtime, data, and other services.",
            "metadata": {"acceptedBy": ["betting", "airtime", "data", "services"]},
        },
        {
            "provider": "Ringas Voucher",
            "name": "Ringas Voucher R100",
            "category": "betting",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("100.00"),
            "sale_price": Decimal("100.00"),
            "currency": "ZAR",
            "requires_recipient": False,
            "recipient_label": "",
            "notes": "Accepted at Betway and selected other bookmakers.",
            "metadata": {"acceptedBy": ["betway"]},
        },
        {
            "provider": "Pay@ Voucher",
            "name": "Pay@ Voucher R100",
            "category": "betting",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("100.00"),
            "sale_price": Decimal("100.00"),
            "currency": "ZAR",
            "requires_recipient": False,
            "recipient_label": "",
            "notes": "Used at selected operators within the Pay@ network.",
            "metadata": {"acceptedBy": ["payat-network"]},
        },
        {
            "provider": "aCoin Voucher",
            "name": "aCoin Voucher R100",
            "category": "betting",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("100.00"),
            "sale_price": Decimal("100.00"),
            "currency": "ZAR",
            "requires_recipient": False,
            "recipient_label": "",
            "notes": "Accepted on selected Playabets-linked sites.",
            "metadata": {"acceptedBy": ["playabets-linked-sites"]},
        },
        {
            "provider": "Shoprite",
            "name": "Shoprite Food Voucher R200",
            "category": "retail",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("200.00"),
            "sale_price": Decimal("200.00"),
            "currency": "ZAR",
            "requires_recipient": False,
            "recipient_label": "",
            "notes": "General grocery voucher for Shoprite purchases.",
            "metadata": {"retailer": "shoprite"},
        },
        {
            "provider": "Checkers",
            "name": "Checkers Food Voucher R200",
            "category": "retail",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("200.00"),
            "sale_price": Decimal("200.00"),
            "currency": "ZAR",
            "requires_recipient": False,
            "recipient_label": "",
            "notes": "General grocery voucher for Checkers purchases.",
            "metadata": {"retailer": "checkers"},
        },
        {
            "provider": "Pick n Pay",
            "name": "Pick n Pay Voucher R200",
            "category": "retail",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("200.00"),
            "sale_price": Decimal("200.00"),
            "currency": "ZAR",
            "requires_recipient": False,
            "recipient_label": "",
            "notes": "General retail voucher for Pick n Pay.",
            "metadata": {"retailer": "pick-n-pay"},
        },
        {
            "provider": "Spar",
            "name": "Spar Voucher R200",
            "category": "retail",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("200.00"),
            "sale_price": Decimal("200.00"),
            "currency": "ZAR",
            "requires_recipient": False,
            "recipient_label": "",
            "notes": "General grocery voucher for Spar.",
            "metadata": {"retailer": "spar"},
        },
        {
            "provider": "Woolworths",
            "name": "Woolworths Gift Card R250",
            "category": "retail",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("250.00"),
            "sale_price": Decimal("250.00"),
            "currency": "ZAR",
            "requires_recipient": False,
            "recipient_label": "",
            "notes": "Retail gift card for Woolworths.",
            "metadata": {"retailer": "woolworths"},
        },
        {
            "provider": "Pep / Ackermans",
            "name": "Pep / Ackermans Gift Voucher R150",
            "category": "retail",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("150.00"),
            "sale_price": Decimal("150.00"),
            "currency": "ZAR",
            "requires_recipient": False,
            "recipient_label": "",
            "notes": "Fashion and essentials gift voucher.",
            "metadata": {"retailer": "pep-ackermans"},
        },
        {
            "provider": "KFC",
            "name": "KFC e-Voucher R120",
            "category": "food",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("120.00"),
            "sale_price": Decimal("120.00"),
            "currency": "ZAR",
            "requires_recipient": False,
            "recipient_label": "",
            "notes": "Takeaway food voucher for KFC.",
            "metadata": {"restaurant": "kfc"},
        },
        {
            "provider": "McDonald's",
            "name": "McDonald's Meal Voucher R120",
            "category": "food",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("120.00"),
            "sale_price": Decimal("120.00"),
            "currency": "ZAR",
            "requires_recipient": False,
            "recipient_label": "",
            "notes": "Meal voucher for McDonald's.",
            "metadata": {"restaurant": "mcdonalds"},
        },
        {
            "provider": "Debonairs",
            "name": "Debonairs Voucher R150",
            "category": "food",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("150.00"),
            "sale_price": Decimal("150.00"),
            "currency": "ZAR",
            "requires_recipient": False,
            "recipient_label": "",
            "notes": "Food voucher for Debonairs.",
            "metadata": {"restaurant": "debonairs"},
        },
        {
            "provider": "Steers",
            "name": "Steers Voucher R150",
            "category": "food",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("150.00"),
            "sale_price": Decimal("150.00"),
            "currency": "ZAR",
            "requires_recipient": False,
            "recipient_label": "",
            "notes": "Food voucher for Steers.",
            "metadata": {"restaurant": "steers"},
        },
        {
            "provider": "Nando's",
            "name": "Nando's Voucher R150",
            "category": "food",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("150.00"),
            "sale_price": Decimal("150.00"),
            "currency": "ZAR",
            "requires_recipient": False,
            "recipient_label": "",
            "notes": "Food voucher for Nando's.",
            "metadata": {"restaurant": "nandos"},
        },
        {
            "provider": "Mr D Food",
            "name": "Mr D Food Voucher R150",
            "category": "food",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("150.00"),
            "sale_price": Decimal("150.00"),
            "currency": "ZAR",
            "requires_recipient": False,
            "recipient_label": "",
            "notes": "Food delivery voucher for Mr D Food.",
            "metadata": {"service": "mr-d-food"},
        },
        {
            "provider": "Pearson VUE",
            "name": "Pearson VUE Exam Voucher",
            "category": "exam",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("2500.00"),
            "sale_price": Decimal("2500.00"),
            "currency": "ZAR",
            "requires_recipient": True,
            "recipient_label": "Candidate email",
            "notes": "Exam voucher for Microsoft, AWS, CompTIA, Cisco, and other Pearson VUE exams.",
            "metadata": {"examProviders": ["microsoft", "aws", "comptia", "cisco"]},
        },
        {
            "provider": "Certiport",
            "name": "Certiport Exam Voucher",
            "category": "exam",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("1800.00"),
            "sale_price": Decimal("1800.00"),
            "currency": "ZAR",
            "requires_recipient": True,
            "recipient_label": "Candidate email",
            "notes": "Exam voucher for MOS, Adobe, and IT Specialist exams.",
            "metadata": {"examProviders": ["mos", "adobe", "it-specialist"]},
        },
        {
            "provider": "PSI",
            "name": "PSI Exam Voucher",
            "category": "exam",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("2200.00"),
            "sale_price": Decimal("2200.00"),
            "currency": "ZAR",
            "requires_recipient": True,
            "recipient_label": "Candidate email",
            "notes": "Exam voucher for PSI-delivered professional exams.",
            "metadata": {"examProviders": ["psi"]},
        },
        {
            "provider": "Udemy",
            "name": "Udemy Gift Code R500",
            "category": "learning",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("500.00"),
            "sale_price": Decimal("500.00"),
            "currency": "ZAR",
            "requires_recipient": True,
            "recipient_label": "Recipient email",
            "notes": "Learning voucher for Udemy course access.",
            "metadata": {"platform": "udemy"},
        },
        {
            "provider": "Coursera",
            "name": "Coursera Voucher R500",
            "category": "learning",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("500.00"),
            "sale_price": Decimal("500.00"),
            "currency": "ZAR",
            "requires_recipient": True,
            "recipient_label": "Recipient email",
            "notes": "Learning voucher for Coursera subscriptions and courses.",
            "metadata": {"platform": "coursera"},
        },
        {
            "provider": "LinkedIn Learning",
            "name": "LinkedIn Learning Voucher R500",
            "category": "learning",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("500.00"),
            "sale_price": Decimal("500.00"),
            "currency": "ZAR",
            "requires_recipient": True,
            "recipient_label": "Recipient email",
            "notes": "Learning voucher for LinkedIn Learning access.",
            "metadata": {"platform": "linkedin-learning"},
        },
        {
            "provider": "MTN",
            "name": "MTN Data Voucher R99",
            "category": "data",
            "delivery_type": "topup",
            "face_value": Decimal("99.00"),
            "sale_price": Decimal("99.00"),
            "currency": "ZAR",
            "requires_recipient": True,
            "recipient_label": "Phone number",
            "notes": "Mobile data voucher for MTN.",
            "metadata": {"network": "mtn"},
        },
        {
            "provider": "Vodacom",
            "name": "Vodacom Data Voucher R99",
            "category": "data",
            "delivery_type": "topup",
            "face_value": Decimal("99.00"),
            "sale_price": Decimal("99.00"),
            "currency": "ZAR",
            "requires_recipient": True,
            "recipient_label": "Phone number",
            "notes": "Mobile data voucher for Vodacom.",
            "metadata": {"network": "vodacom"},
        },
        {
            "provider": "Telkom",
            "name": "Telkom Airtime Voucher R50",
            "category": "airtime",
            "delivery_type": "topup",
            "face_value": Decimal("50.00"),
            "sale_price": Decimal("50.00"),
            "currency": "ZAR",
            "requires_recipient": True,
            "recipient_label": "Phone number",
            "notes": "Airtime voucher for Telkom.",
            "metadata": {"network": "telkom"},
        },
        {
            "provider": "Cell C",
            "name": "Cell C Airtime Voucher R50",
            "category": "airtime",
            "delivery_type": "topup",
            "face_value": Decimal("50.00"),
            "sale_price": Decimal("50.00"),
            "currency": "ZAR",
            "requires_recipient": True,
            "recipient_label": "Phone number",
            "notes": "Airtime voucher for Cell C.",
            "metadata": {"network": "cell-c"},
        },
        {
            "provider": "Eskom",
            "name": "Eskom Prepaid Electricity Token R200",
            "category": "electricity",
            "delivery_type": "pin",
            "face_value": Decimal("200.00"),
            "sale_price": Decimal("200.00"),
            "currency": "ZAR",
            "requires_recipient": True,
            "recipient_label": "Meter number",
            "notes": "Prepaid electricity token for Eskom meters.",
            "metadata": {"utility": "eskom"},
        },
        {
            "provider": "Municipal",
            "name": "Municipal Prepaid Electricity Voucher R200",
            "category": "electricity",
            "delivery_type": "pin",
            "face_value": Decimal("200.00"),
            "sale_price": Decimal("200.00"),
            "currency": "ZAR",
            "requires_recipient": True,
            "recipient_label": "Meter number",
            "notes": "Prepaid electricity voucher for municipal billing systems.",
            "metadata": {"utility": "municipal"},
        },
        {
            "provider": "Netflix",
            "name": "Netflix Gift Code R200",
            "category": "entertainment",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("200.00"),
            "sale_price": Decimal("200.00"),
            "currency": "ZAR",
            "requires_recipient": True,
            "recipient_label": "Recipient email",
            "notes": "Entertainment voucher for Netflix.",
            "metadata": {"platform": "netflix"},
        },
        {
            "provider": "Spotify",
            "name": "Spotify Voucher R150",
            "category": "entertainment",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("150.00"),
            "sale_price": Decimal("150.00"),
            "currency": "ZAR",
            "requires_recipient": True,
            "recipient_label": "Recipient email",
            "notes": "Entertainment voucher for Spotify.",
            "metadata": {"platform": "spotify"},
        },
        {
            "provider": "PlayStation",
            "name": "PlayStation Store Gift Card R250",
            "category": "entertainment",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("250.00"),
            "sale_price": Decimal("250.00"),
            "currency": "ZAR",
            "requires_recipient": False,
            "recipient_label": "",
            "notes": "Gaming gift card for PlayStation Store.",
            "metadata": {"platform": "playstation"},
        },
        {
            "provider": "Xbox",
            "name": "Xbox Gift Card R250",
            "category": "entertainment",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("250.00"),
            "sale_price": Decimal("250.00"),
            "currency": "ZAR",
            "requires_recipient": False,
            "recipient_label": "",
            "notes": "Gaming gift card for Xbox.",
            "metadata": {"platform": "xbox"},
        },
        {
            "provider": "Steam",
            "name": "Steam Wallet Code R250",
            "category": "entertainment",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("250.00"),
            "sale_price": Decimal("250.00"),
            "currency": "ZAR",
            "requires_recipient": False,
            "recipient_label": "",
            "notes": "Gaming wallet code for Steam.",
            "metadata": {"platform": "steam"},
        },
        {
            "provider": "Uber",
            "name": "Uber Gift Card R200",
            "category": "transport",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("200.00"),
            "sale_price": Decimal("200.00"),
            "currency": "ZAR",
            "requires_recipient": True,
            "recipient_label": "Recipient email",
            "notes": "Transport gift card for Uber rides.",
            "metadata": {"service": "uber"},
        },
        {
            "provider": "Bolt",
            "name": "Bolt Ride Voucher R200",
            "category": "transport",
            "delivery_type": "digital_voucher",
            "face_value": Decimal("200.00"),
            "sale_price": Decimal("200.00"),
            "currency": "ZAR",
            "requires_recipient": True,
            "recipient_label": "Recipient email",
            "notes": "Transport voucher for Bolt rides.",
            "metadata": {"service": "bolt"},
        },
    ]

    for item in items:
        VoucherCatalogItem.objects.update_or_create(
            provider=item["provider"],
            name=item["name"],
            defaults=item,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_exam_voucher_catalog_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vouchercatalogitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("airtime", "Airtime"),
                    ("betting", "Betting"),
                    ("retail", "Retail"),
                    ("food", "Food"),
                    ("data", "Data"),
                    ("entertainment", "Entertainment"),
                    ("exam", "Exam"),
                    ("learning", "Learning"),
                    ("electricity", "Electricity"),
                    ("transport", "Transport"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=24,
            ),
        ),
        migrations.RunPython(seed_expanded_voucher_catalog, migrations.RunPython.noop),
    ]