# Generated by Django 5.2.8 on 2026-03-29 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_seed_voucher_network_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="Debt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creditor", models.CharField(max_length=120)),
                (
                    "debt_type",
                    models.CharField(
                        choices=[
                            ("personal_loan", "Personal Loan"),
                            ("store_credit", "Store Credit"),
                            ("vehicle_finance", "Vehicle Finance"),
                            ("home_loan", "Home Loan"),
                            ("medical", "Medical"),
                            ("credit_card", "Credit Card"),
                            ("student_loan", "Student Loan"),
                            ("business_loan", "Business Loan"),
                            ("utility", "Utility / Municipal"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "original_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "outstanding_balance",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "monthly_installment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Annual % rate",
                        max_digits=5,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("current", "Current"),
                            ("overdue", "Overdue"),
                            ("paid", "Paid"),
                            ("written_off", "Written Off"),
                            ("in_dispute", "In Dispute"),
                        ],
                        default="current",
                        max_length=15,
                    ),
                ),
                ("months_overdue", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("reference", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Debtor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("id_number", models.CharField(max_length=13, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.RenameIndex(
            model_name="merchantpartner",
            new_name="core_mercha_slug_aef900_idx",
            old_name="core_mercha_slug_3e4706_idx",
        ),
        migrations.RenameIndex(
            model_name="providerintegration",
            new_name="core_provid_provide_555d2c_idx",
            old_name="core_provid_provide_72f6d0_idx",
        ),
        migrations.RenameIndex(
            model_name="providerwebhookevent",
            new_name="core_provid_provide_9f3e01_idx",
            old_name="core_provid_provide_9e2328_idx",
        ),
        migrations.RenameIndex(
            model_name="providerwebhookevent",
            new_name="core_provid_referen_74925b_idx",
            old_name="core_provid_referen_010ea1_idx",
        ),
        migrations.RenameIndex(
            model_name="voucher",
            new_name="core_vouche_code_9ce1f6_idx",
            old_name="core_vouche_code_2f8142_idx",
        ),
        migrations.RenameIndex(
            model_name="voucher",
            new_name="core_vouche_voucher_272577_idx",
            old_name="core_vouche_voucher_4b7b52_idx",
        ),
        migrations.RenameIndex(
            model_name="voucher",
            new_name="core_vouche_is_acti_66511c_idx",
            old_name="core_vouche_is_acti_25e315_idx",
        ),
        migrations.RenameIndex(
            model_name="vouchercatalogitem",
            new_name="core_vouche_categor_ee9fc0_idx",
            old_name="core_vouche_categor_4b332a_idx",
        ),
        migrations.RenameIndex(
            model_name="vouchercatalogitem",
            new_name="core_vouche_is_acti_64ae8c_idx",
            old_name="core_vouche_is_acti_03b936_idx",
        ),
        migrations.RenameIndex(
            model_name="voucherpurchase",
            new_name="core_vouche_referen_11ec10_idx",
            old_name="core_vouche_referen_b3bc83_idx",
        ),
        migrations.RenameIndex(
            model_name="voucherpurchase",
            new_name="core_vouche_status_a2b6b6_idx",
            old_name="core_vouche_status_7f8c40_idx",
        ),
        migrations.RenameIndex(
            model_name="voucherredemption",
            new_name="core_vouche_referen_d719e4_idx",
            old_name="core_vouche_referen_8d6337_idx",
        ),
        migrations.RenameIndex(
            model_name="voucherredemption",
            new_name="core_vouche_channel_a8aa69_idx",
            old_name="core_vouche_channel_8565b3_idx",
        ),
        migrations.AddIndex(
            model_name="debtor",
            index=models.Index(
                fields=["id_number"], name="core_debtor_id_numb_332c72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="debtor",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="core_debtor_last_na_c986bb_idx",
            ),
        ),
        migrations.AddField(
            model_name="debt",
            name="debtor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="debts",
                to="core.debtor",
            ),
        ),
        migrations.AddIndex(
            model_name="debt",
            index=models.Index(
                fields=["debtor", "status"], name="core_debt_debtor__fecef1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="debt",
            index=models.Index(fields=["status"], name="core_debt_status_971140_idx"),
        ),
    ]
