from django.urls import path

from .views import (
    ai_suite_dub_cues,
    ai_suite_moderate,
    ai_suite_review_approve,
    ai_suite_review_submit,
    ai_suite_soundtrack,
    ai_suite_webhook_test,
    credit_check_portal,
    credit_check_lookup,
    credit_check_add_debtor,
    credit_check_add_debt,
    cap_anime_generate_image,
    cap_anime_generate_script,
    cap_anime_generate_video,
    cap_anime_media_file,
    bab_watch_discover,
    bab_watch_genres,
    bab_watch_providers,
    bab_watch_recommendations,
    bab_watch_trending,
    bab_watch_trailer,
    bab_watch_watch_link,
    create_pest_lead,
    market_analyze,
    market_analyze_all,
    market_analyzer_dashboard,
    market_alert_logs,
    market_backtest,
    market_prediction_clear,
    market_prediction_history,
    market_learning_insights,
    market_paper_account,
    market_prediction_stats,
    market_provider_health_summary,
    market_providers,
    market_symbols,
    pest_lead_dashboard,
    pest_lead_list,
    voucher_generate,
    voucher_list,
    voucher_merchant_profile,
    voucher_merchant_quote,
    voucher_merchant_redeem,
    voucher_products,
    voucher_purchase,
    voucher_provider_integrations,
    voucher_provider_webhook,
    voucher_reporting_dashboard,
    voucher_reporting_data,
    voucher_redeem,
    voucher_validate,
    voucher_zone,
)

urlpatterns = [
    path("api/cap-anime/generate-image/", cap_anime_generate_image, name="cap_anime_generate_image"),
    path("api/cap-anime/generate-script/", cap_anime_generate_script, name="cap_anime_generate_script"),
    path("api/cap-anime/generate-video/", cap_anime_generate_video, name="cap_anime_generate_video"),
    path("api/cap-anime/media/<str:media_group>/<str:filename>", cap_anime_media_file, name="cap_anime_media_file"),
    path("api/ai-suite/moderate/", ai_suite_moderate, name="ai_suite_moderate"),
    path("api/ai-suite/dub-cues/", ai_suite_dub_cues, name="ai_suite_dub_cues"),
    path("api/ai-suite/soundtrack/", ai_suite_soundtrack, name="ai_suite_soundtrack"),
    path("api/ai-suite/review/submit/", ai_suite_review_submit, name="ai_suite_review_submit"),
    path("api/ai-suite/review/approve/", ai_suite_review_approve, name="ai_suite_review_approve"),
    path("api/ai-suite/webhook/test/", ai_suite_webhook_test, name="ai_suite_webhook_test"),
    path("api/pest-leads/", create_pest_lead, name="create_pest_lead"),
    path("api/pest-leads/list/", pest_lead_list, name="pest_lead_list"),
    path("api/bab-watch/genres/", bab_watch_genres, name="bab_watch_genres"),
    path("api/bab-watch/providers/", bab_watch_providers, name="bab_watch_providers"),
    path("api/bab-watch/discover/", bab_watch_discover, name="bab_watch_discover"),
    path("api/bab-watch/trending/", bab_watch_trending, name="bab_watch_trending"),
    path("api/bab-watch/trailer/", bab_watch_trailer, name="bab_watch_trailer"),
    path("api/bab-watch/watch-link/", bab_watch_watch_link, name="bab_watch_watch_link"),
    path("api/bab-watch/recommendations/", bab_watch_recommendations, name="bab_watch_recommendations"),
    path("api/market/symbols/", market_symbols, name="market_symbols"),
    path("api/market/providers/", market_providers, name="market_providers"),
    path("api/market/analyze/", market_analyze, name="market_analyze"),
    path("api/market/analyze-all/", market_analyze_all, name="market_analyze_all"),
    path("api/market/backtest/", market_backtest, name="market_backtest"),
    path("api/market/predictions/history/", market_prediction_history, name="market_prediction_history"),
    path("api/market/predictions/learning/", market_learning_insights, name="market_learning_insights"),
    path("api/market/paper-account/", market_paper_account, name="market_paper_account"),
    path("api/market/predictions/stats/", market_prediction_stats, name="market_prediction_stats"),
    path("api/market/predictions/clear/", market_prediction_clear, name="market_prediction_clear"),
    path("api/market/provider-health/", market_provider_health_summary, name="market_provider_health_summary"),
    path("api/market/alert-logs/", market_alert_logs, name="market_alert_logs"),
    path("api/vouchers/", voucher_list, name="voucher_list"),
    path("api/vouchers/generate/", voucher_generate, name="voucher_generate"),
    path("api/vouchers/merchant/profile/", voucher_merchant_profile, name="voucher_merchant_profile"),
    path("api/vouchers/merchant/quote/", voucher_merchant_quote, name="voucher_merchant_quote"),
    path("api/vouchers/merchant/redeem/", voucher_merchant_redeem, name="voucher_merchant_redeem"),
    path("api/vouchers/products/", voucher_products, name="voucher_products"),
    path("api/vouchers/purchase/", voucher_purchase, name="voucher_purchase"),
    path("api/vouchers/providers/integrations/", voucher_provider_integrations, name="voucher_provider_integrations"),
    path("api/vouchers/providers/webhook/<slug:provider_slug>/", voucher_provider_webhook, name="voucher_provider_webhook"),
    path("api/vouchers/reporting/", voucher_reporting_data, name="voucher_reporting_data"),
    path("api/vouchers/validate/", voucher_validate, name="voucher_validate"),
    path("api/vouchers/redeem/", voucher_redeem, name="voucher_redeem"),
    path("market-analyzer/", market_analyzer_dashboard, name="market_analyzer_dashboard"),
    path("pest-control/dashboard/", pest_lead_dashboard, name="pest_lead_dashboard"),
    path("Voucher-Zone/", voucher_zone, name="voucher_zone"),
    path("Voucher-Zone/reporting/", voucher_reporting_dashboard, name="voucher_reporting_dashboard"),
    path("credit-check/", credit_check_portal, name="credit_check_portal"),
    path("api/credit-check/lookup/", credit_check_lookup, name="credit_check_lookup"),
    path("api/credit-check/debtors/add/", credit_check_add_debtor, name="credit_check_add_debtor"),
    path("api/credit-check/debts/add/", credit_check_add_debt, name="credit_check_add_debt"),
]
